### ISSUE TITLE
valid graph creates python runtime error

### ISSUE THREAD

**Issue by vilterp** [vilterp/thesis#16]
![screen shot 2015-05-21 at 3 21 02 am](https://cloud.githubusercontent.com/assets/7341/7744443/dab73b02-ff68-11e4-873e-0c90cdb3bfa8.png)

code:

``` python
from log_call import *

def Map(function, list):
  arg_name = function.func_code.co_varnames[0]
  def apply_single(item):
    result = log_call(function, 'map_internal', {arg_name: item})
    return result.values()[0]
  return {'mappedList': map(apply_single, list)}

def add_excl(str):
  return {'added':str + '!'}

def add_hi(str):
  return {'added': 'Hi ' + str}

def main():
  ap0_names = log_call(names, "ap0_names", {})
  ap0_names_names = ap0_names["names"]
  def lambda0(lambda0_ap2_add_hi_str):
    lambda0_ap1_add_excl = log_call(add_excl, "ap1_add_excl", {"str": lambda0_ap2_add_hi_added})
    lambda0_ap1_add_excl_added = lambda0_ap1_add_excl["added"]
    lambda0_ap2_add_hi = log_call(add_hi, "ap2_add_hi", {"str": lambda0_ap2_add_hi_str})
    lambda0_ap2_add_hi_added = lambda0_ap2_add_hi["added"]
    return {"lambda0_ap1_add_excl_added": lambda0_ap1_add_excl_added}
  ap3_map = log_call(Map, "ap3_map", {"function": lambda0, "list": ap0_names_names})
  ap3_map_mappedList = ap3_map["mappedList"]
  ap4_newline_join = log_call(newline_join, "ap4_newline_join", {"list": ap3_map_mappedList})
  ap4_newline_join_joinedList = ap4_newline_join["joinedList"]
  return {"ap4_newline_join_joinedList": ap4_newline_join_joinedList}

def names():
  return {'names':['Pete', 'Borja', 'Ravi', 'Mike']}

def newline_join(list):
  return {'joinedList': '\n'.join(list)}

run_main(main, {})
```

traceback:

```
python err: Traceback (most recent call last):
  File "/var/folders/bj/knv1l7bn18gd24860zt2x6p40000gn/T/tmp-17631DqtiQBPwLGh6/code.py", line 37, in <module>
    run_main(main, {})
  File "/private/var/folders/bj/knv1l7bn18gd24860zt2x6p40000gn/T/tmp-17631DqtiQBPwLGh6/log_call.py", line 70, in run_main
    result = fun(**args)
  File "/var/folders/bj/knv1l7bn18gd24860zt2x6p40000gn/T/tmp-17631DqtiQBPwLGh6/code.py", line 25, in main
    ap3_map = log_call(Map, "ap3_map", {"function": lambda0, "list": ap0_names_names})
  File "/private/var/folders/bj/knv1l7bn18gd24860zt2x6p40000gn/T/tmp-17631DqtiQBPwLGh6/log_call.py", line 63, in log_call
    result = function(**args)
  File "/var/folders/bj/knv1l7bn18gd24860zt2x6p40000gn/T/tmp-17631DqtiQBPwLGh6/code.py", line 8, in Map
    return {'mappedList': map(apply_single, list)}
  File "/var/folders/bj/knv1l7bn18gd24860zt2x6p40000gn/T/tmp-17631DqtiQBPwLGh6/code.py", line 6, in apply_single
    result = log_call(function, 'map_internal', {arg_name: item})
  File "/private/var/folders/bj/knv1l7bn18gd24860zt2x6p40000gn/T/tmp-17631DqtiQBPwLGh6/log_call.py", line 63, in log_call
    result = function(**args)
  File "/var/folders/bj/knv1l7bn18gd24860zt2x6p40000gn/T/tmp-17631DqtiQBPwLGh6/code.py", line 20, in lambda0
    lambda0_ap1_add_excl = log_call(add_excl, "ap1_add_excl", {"str": lambda0_ap2_add_hi_added})
UnboundLocalError: local variable 'lambda0_ap2_add_hi_added' referenced before assignment
```

**Comment by vilterp** [comment]
Fixed by d0df52e4bc3a67446101bc1bc25de4dd00921342
